version: '3'

services:
  simple-nginx:
    hostname: simple-nginx
    container_name: simple-nginx
    image: nginx:latest
    networks:
      - proxy
    ports:
      # (Un)Comment options based on need
      - 80 # Expose port only on docker network
      # - 80:80 # Expose port on the host
      # - 443:443 # Expose port on the host
    volumes:
      - ./html/:/usr/share/nginx/html

networks:
  proxy:
    external: true
